version: "3"
# Named volumes that can be re-used between services
volumes:
  # Create a volume to contain the mysql data
  mysql-volume:

services:
  # The name of our built service
  ghost:
    # Configuration options applied when the image is built
    build:
      # Path to where the Dockerfile is located
      context: .
    # Automaticlaly restart the service if it crashes
    restart: always
    # Map a port inside the image externally so we can access services hosted in the image (external:internal)
    ports:
      - 3001:2368
    # Set environment variables to pass to the image
    environment:
      # This is Ghost specific configuration
      - url=http://localhost:3001/
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=blog-user
      - database__connection__password=supersecret
      - database__connection__database=db
    depends_on:
      - mysql
    # Override the default start script 
    entrypoint: ["wait-for-mysql.sh", "mysql", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
  mysql:
    # Instead of a local docker file we are going to use the standard prepacked mysql docker image
    image: mysql:5.7
    # Use the named volume above to persist data
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      # Use environment variables to setup an initial database and user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: supersecret